url: "https://taxtracker.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "taxtracker.org"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json